// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {sync, host} from '../models';

export function ApplySync():Promise<sync.MergeResult>;
export function ChangePassword(arg1:string,arg2:string):Promise<void>;
export function CheckSyncPending():Promise<sync.MergeResult>;
export function CreateGroup(arg1:string,arg2:number):Promise<host.Group>;
export function CreateHost(arg1:host.HostInput):Promise<host.Host>;
export function DeleteGroup(arg1:string):Promise<void>;
export function DeleteHost(arg1:string):Promise<void>;
export function Greet(arg1:string):Promise<string>;
export function IsInitialized():Promise<boolean>;
export function ListGroups():Promise<Array<host.Group>>;
export function ListHosts():Promise<Array<host.Host>>;
export function Setup(arg1:string):Promise<void>;
export function Unlock(arg1:string):Promise<void>;
export function UpdateGroup(arg1:string,arg2:string,arg3:number):Promise<host.Group>;
export function UpdateHost(arg1:string,arg2:host.HostInput):Promise<host.Host>;
