// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySync() {
  return window['go']['main']['App']['ApplySync']();
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CheckSyncPending() {
  return window['go']['main']['App']['CheckSyncPending']();
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateHost(arg1) {
  return window['go']['main']['App']['CreateHost'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function Setup(arg1) {
  return window['go']['main']['App']['Setup'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2, arg3);
}

export function UpdateHost(arg1, arg2) {
  return window['go']['main']['App']['UpdateHost'](arg1, arg2);
}
