// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsInitialized():Promise<boolean>;

export function Setup(arg1:string):Promise<void>;

export function Unlock(arg1:string):Promise<void>;
