// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sshkey} from '../models';
import {sync} from '../models';
import {host} from '../models';
import {snippet} from '../models';
import {team} from '../models';
import {ai} from '../models';
import {audit} from '../models';

export function AckTerminal(arg1:string,arg2:number):Promise<void>;

export function AddSSHKey(arg1:string,arg2:string):Promise<sshkey.SSHKey>;

export function ApplySync():Promise<sync.MergeResult>;

export function AskAI(arg1:string):Promise<string>;

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function CheckSyncPending():Promise<sync.MergeResult>;

export function ClearAuditLogs(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function ConnectTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function CreateGroup(arg1:string,arg2:number):Promise<host.Group>;

export function CreateHost(arg1:host.HostInput):Promise<host.Host>;

export function CreateSnippet(arg1:snippet.SnippetInput):Promise<snippet.Snippet>;

export function CreateTeam(arg1:team.TeamInput):Promise<team.Team>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteSSHKey(arg1:string):Promise<void>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function DeleteTeam(arg1:string):Promise<void>;

export function GenerateSSHKey(arg1:string,arg2:number):Promise<sshkey.SSHKey>;

export function GetAIConfig():Promise<ai.Config>;

export function GetSSHKey(arg1:string):Promise<sshkey.SSHKey>;

export function GetSyncPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HardDeleteRecord(arg1:string,arg2:string):Promise<void>;

export function IsInitialized():Promise<boolean>;

export function ListAuditLogs(arg1:string,arg2:number,arg3:number):Promise<Array<audit.AuditLog>>;

export function ListGroups():Promise<Array<host.Group>>;

export function ListHosts():Promise<Array<host.Host>>;

export function ListSSHKeys():Promise<Array<sshkey.SSHKey>>;

export function ListSnippets():Promise<Array<snippet.Snippet>>;

export function ListTeams():Promise<Array<team.Team>>;

export function LogCommand(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function OpenDonationLink():Promise<void>;

export function ResetVault():Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveAIConfig(arg1:ai.Config):Promise<void>;

export function Setup(arg1:string):Promise<void>;

export function Unlock(arg1:string):Promise<void>;

export function UpdateGroup(arg1:string,arg2:string,arg3:number):Promise<host.Group>;

export function UpdateHost(arg1:string,arg2:host.HostInput):Promise<host.Host>;

export function UpdateSnippet(arg1:string,arg2:snippet.SnippetInput):Promise<snippet.Snippet>;

export function UpdateTeam(arg1:string,arg2:team.TeamInput):Promise<team.Team>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
