// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function Setup(arg1) {
  return window['go']['main']['App']['Setup'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}
