// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSSHKey(arg1, arg2) {
  return window['go']['main']['App']['AddSSHKey'](arg1, arg2);
}

export function ApplySync() {
  return window['go']['main']['App']['ApplySync']();
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CheckSyncPending() {
  return window['go']['main']['App']['CheckSyncPending']();
}

export function ClearAuditLogs(arg1) {
  return window['go']['main']['App']['ClearAuditLogs'](arg1);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateHost(arg1) {
  return window['go']['main']['App']['CreateHost'](arg1);
}

export function CreateSnippet(arg1) {
  return window['go']['main']['App']['CreateSnippet'](arg1);
}

export function CreateTeam(arg1) {
  return window['go']['main']['App']['CreateTeam'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function DeleteSSHKey(arg1) {
  return window['go']['main']['App']['DeleteSSHKey'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['main']['App']['DeleteTeam'](arg1);
}

export function GenerateSSHKey(arg1, arg2) {
  return window['go']['main']['App']['GenerateSSHKey'](arg1, arg2);
}

export function GetSSHKey(arg1) {
  return window['go']['main']['App']['GetSSHKey'](arg1);
}

export function GetSyncPath() {
  return window['go']['main']['App']['GetSyncPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HardDeleteRecord(arg1, arg2) {
  return window['go']['main']['App']['HardDeleteRecord'](arg1, arg2);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function ListAuditLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAuditLogs'](arg1, arg2, arg3);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function ListSSHKeys() {
  return window['go']['main']['App']['ListSSHKeys']();
}

export function ListSnippets() {
  return window['go']['main']['App']['ListSnippets']();
}

export function ListTeams() {
  return window['go']['main']['App']['ListTeams']();
}

export function LogCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogCommand'](arg1, arg2, arg3, arg4);
}

export function OpenDonationLink() {
  return window['go']['main']['App']['OpenDonationLink']();
}

export function ResetVault() {
  return window['go']['main']['App']['ResetVault']();
}

export function Setup(arg1) {
  return window['go']['main']['App']['Setup'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2, arg3);
}

export function UpdateHost(arg1, arg2) {
  return window['go']['main']['App']['UpdateHost'](arg1, arg2);
}

export function UpdateSnippet(arg1, arg2) {
  return window['go']['main']['App']['UpdateSnippet'](arg1, arg2);
}

export function UpdateTeam(arg1, arg2) {
  return window['go']['main']['App']['UpdateTeam'](arg1, arg2);
}
